/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproject.view;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaproject.utill.ConfigDB;
import javax.swing.table.DefaultTableModel;
import javaproject.utill.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/**
 *
 * @author itsly
 */
public class Dashboard extends javax.swing.JFrame {
    // Membuat Class dimana semua method tersimpan sesuai dengan page yang diperlukan
    FilmUtill film;
    AnggotaUtill anggota;
    TransaksiUtill transaksi;
    
    int page = 1;
    
    public Dashboard() {
        initComponents();
        
        film = new FilmUtill(tableDisplay, iKodeFilm, iJudulFilm, iGenreFilm, iAsalFilm, iStokFilm, iTahunFilm, iSearch);
        anggota = new AnggotaUtill(tableDisplay, iIdAnggota, iNamaAnggota, iTempatLahirAnggota, iTanggalLahirAnggota, iKelaminAnggota, iStatusAnggota, iAlamatAnggota, iNomorTeleponAnggota, iSearch);
        transaksi = new TransaksiUtill(tableDisplay, tableDisplay1, iIdAnggotaTransaksi, iIdFilmTransaksi, iIdPinjamTransaksi, iNamaAnggotaTransaksi, iJudulFilmTransaksi, iTanggalPinjamTransaksi, iTanggalKembaliTransaksi, iDendaTransaksi, lIdDetailTransaksi, iSearch);
        
        choosePage(page);
    }
    
    private void choosePage(int page) {
        if (page == 1) {
            FilmMaster.setVisible(true);
            AnggotaMaster.setVisible(false);
            TransaksiMaster.setVisible(false);
            container2.setVisible(false);
            
            film.tampilTabelFilm();
        } else if (page == 2) {
            FilmMaster.setVisible(false);
            AnggotaMaster.setVisible(true);
            TransaksiMaster.setVisible(false);
            container2.setVisible(false);

            anggota.tampilTabelAnggota();
        } else if (page == 3) {
            FilmMaster.setVisible(false);
            AnggotaMaster.setVisible(false);
            TransaksiMaster.setVisible(true);
            container2.setVisible(true);
        }
    }
    
    

/**
     * Creates new form Dashboard
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDisplay = new javax.swing.JTable();
        iSearch = new javax.swing.JTextField();
        Form = new javax.swing.JScrollPane();
        Container = new javax.swing.JPanel();
        FilmMaster = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iKodeFilm = new javax.swing.JTextField();
        iJudulFilm = new javax.swing.JTextField();
        iGenreFilm = new javax.swing.JTextField();
        iTahunFilm = new javax.swing.JTextField();
        iAsalFilm = new javax.swing.JTextField();
        iStokFilm = new javax.swing.JTextField();
        btnEditFilm = new javax.swing.JButton();
        btnSimpanFilm = new javax.swing.JButton();
        btnHapusFilm = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnClearInputFilm = new javax.swing.JButton();
        AnggotaMaster = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        iIdAnggota = new javax.swing.JTextField();
        iNamaAnggota = new javax.swing.JTextField();
        iTempatLahirAnggota = new javax.swing.JTextField();
        iAlamatAnggota = new javax.swing.JTextField();
        iNomorTeleponAnggota = new javax.swing.JTextField();
        btnEditAnggota = new javax.swing.JButton();
        btnTambahAnggota = new javax.swing.JButton();
        btnHapusAnggota = new javax.swing.JButton();
        iKelaminAnggota = new javax.swing.JComboBox<>();
        iStatusAnggota = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnClearAnggota = new javax.swing.JButton();
        iTanggalLahirAnggota = new com.toedter.calendar.JDateChooser();
        TransaksiMaster = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        iIdAnggotaTransaksi = new javax.swing.JTextField();
        iEditTransaksi = new javax.swing.JButton();
        btnTambahTransaksi = new javax.swing.JButton();
        iHapusTransaksi = new javax.swing.JButton();
        iIdPinjamTransaksi = new javax.swing.JTextField();
        btnCariTunggakan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnLogin10 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        iKeteranganTransaksi = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        iTanggalKembaliTransaksi = new com.toedter.calendar.JDateChooser();
        iTanggalPinjamTransaksi = new com.toedter.calendar.JDateChooser();
        iNamaAnggotaTransaksi = new javax.swing.JTextField();
        iJudulFilmTransaksi = new javax.swing.JTextField();
        iIdFilmTransaksi = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        iDendaTransaksi = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        lIdDetailTransaksi = new javax.swing.JLabel();
        clearInputTransaksi = new javax.swing.JButton();
        container2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDisplay1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnFilmPage = new javax.swing.JButton();
        btnAnggotaPage = new javax.swing.JButton();
        btnTransaksiPage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 204, 51));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 102, 51));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel3.setBackground(new java.awt.Color(249, 249, 249));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableDisplay.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        tableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Film", "Judul Film", "Genre Film", "Tahun Film", "Asal Film", "Stok Film"
            }
        ));
        tableDisplay.setToolTipText("");
        tableDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDisplayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDisplay);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 714, 540));

        iSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iSearchActionPerformed(evt);
            }
        });
        iSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                iSearchKeyPressed(evt);
            }
        });
        jPanel3.add(iSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 714, 50));

        Form.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Container.setBackground(new java.awt.Color(249, 249, 249));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("FILM");

        iKodeFilm.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iKodeFilm.setForeground(new java.awt.Color(204, 204, 204));
        iKodeFilm.setToolTipText("");
        iKodeFilm.setName(""); // NOI18N
        iKodeFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iKodeFilmActionPerformed(evt);
            }
        });

        iJudulFilm.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iJudulFilm.setForeground(new java.awt.Color(204, 204, 204));
        iJudulFilm.setToolTipText("");
        iJudulFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iJudulFilmActionPerformed(evt);
            }
        });

        iGenreFilm.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iGenreFilm.setForeground(new java.awt.Color(204, 204, 204));
        iGenreFilm.setToolTipText("");
        iGenreFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iGenreFilmActionPerformed(evt);
            }
        });

        iTahunFilm.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iTahunFilm.setForeground(new java.awt.Color(204, 204, 204));
        iTahunFilm.setToolTipText("");
        iTahunFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iTahunFilmActionPerformed(evt);
            }
        });

        iAsalFilm.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iAsalFilm.setForeground(new java.awt.Color(204, 204, 204));
        iAsalFilm.setToolTipText("");
        iAsalFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAsalFilmActionPerformed(evt);
            }
        });

        iStokFilm.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iStokFilm.setForeground(new java.awt.Color(204, 204, 204));
        iStokFilm.setToolTipText("");
        iStokFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iStokFilmActionPerformed(evt);
            }
        });

        btnEditFilm.setBackground(new java.awt.Color(0, 51, 255));
        btnEditFilm.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnEditFilm.setForeground(new java.awt.Color(255, 255, 255));
        btnEditFilm.setText("EDIT");
        btnEditFilm.setBorder(null);
        btnEditFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFilmActionPerformed(evt);
            }
        });

        btnSimpanFilm.setBackground(new java.awt.Color(0, 153, 51));
        btnSimpanFilm.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnSimpanFilm.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanFilm.setText("TAMBAH");
        btnSimpanFilm.setBorder(null);
        btnSimpanFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanFilmActionPerformed(evt);
            }
        });

        btnHapusFilm.setBackground(new java.awt.Color(255, 0, 0));
        btnHapusFilm.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnHapusFilm.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusFilm.setText("HAPUS");
        btnHapusFilm.setBorder(null);
        btnHapusFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusFilmActionPerformed(evt);
            }
        });

        jLabel11.setText("Kode Film");

        jLabel12.setText("Judul Film");

        jLabel13.setText("Genre Film");

        jLabel14.setText("Tahun Film");

        jLabel15.setText("Asal Film");

        jLabel16.setText("Stok Film");

        btnClearInputFilm.setText("CLEAR");
        btnClearInputFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearInputFilmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FilmMasterLayout = new javax.swing.GroupLayout(FilmMaster);
        FilmMaster.setLayout(FilmMasterLayout);
        FilmMasterLayout.setHorizontalGroup(
            FilmMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilmMasterLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(FilmMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FilmMasterLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(FilmMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(FilmMasterLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(298, 298, 298))
                            .addGroup(FilmMasterLayout.createSequentialGroup()
                                .addGroup(FilmMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(iStokFilm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iAsalFilm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iTahunFilm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iGenreFilm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FilmMasterLayout.createSequentialGroup()
                                        .addGroup(FilmMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(iKodeFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addGroup(FilmMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(FilmMasterLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel12))
                                            .addGroup(FilmMasterLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(iJudulFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(btnClearInputFilm))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(FilmMasterLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(FilmMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FilmMasterLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(FilmMasterLayout.createSequentialGroup()
                                .addGroup(FilmMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FilmMasterLayout.createSequentialGroup()
                        .addComponent(btnHapusFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpanFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        FilmMasterLayout.setVerticalGroup(
            FilmMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilmMasterLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(FilmMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnClearInputFilm))
                .addGap(12, 12, 12)
                .addGroup(FilmMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FilmMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iKodeFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iJudulFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iGenreFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iTahunFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(8, 8, 8)
                .addComponent(iAsalFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iStokFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(FilmMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpanFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("ANGGOTA");

        iIdAnggota.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iIdAnggota.setForeground(new java.awt.Color(204, 204, 204));
        iIdAnggota.setToolTipText("");
        iIdAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iIdAnggotaActionPerformed(evt);
            }
        });

        iNamaAnggota.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iNamaAnggota.setForeground(new java.awt.Color(204, 204, 204));
        iNamaAnggota.setToolTipText("");
        iNamaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iNamaAnggotaActionPerformed(evt);
            }
        });

        iTempatLahirAnggota.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iTempatLahirAnggota.setForeground(new java.awt.Color(204, 204, 204));
        iTempatLahirAnggota.setToolTipText("");
        iTempatLahirAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iTempatLahirAnggotaActionPerformed(evt);
            }
        });

        iAlamatAnggota.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iAlamatAnggota.setForeground(new java.awt.Color(204, 204, 204));
        iAlamatAnggota.setToolTipText("");
        iAlamatAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAlamatAnggotaActionPerformed(evt);
            }
        });

        iNomorTeleponAnggota.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iNomorTeleponAnggota.setForeground(new java.awt.Color(204, 204, 204));
        iNomorTeleponAnggota.setToolTipText("");
        iNomorTeleponAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iNomorTeleponAnggotaActionPerformed(evt);
            }
        });

        btnEditAnggota.setBackground(new java.awt.Color(0, 51, 255));
        btnEditAnggota.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnEditAnggota.setForeground(new java.awt.Color(255, 255, 255));
        btnEditAnggota.setText("EDIT");
        btnEditAnggota.setBorder(null);
        btnEditAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAnggotaActionPerformed(evt);
            }
        });

        btnTambahAnggota.setBackground(new java.awt.Color(0, 153, 51));
        btnTambahAnggota.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnTambahAnggota.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahAnggota.setText("TAMBAH");
        btnTambahAnggota.setBorder(null);
        btnTambahAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahAnggotaActionPerformed(evt);
            }
        });

        btnHapusAnggota.setBackground(new java.awt.Color(255, 0, 0));
        btnHapusAnggota.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnHapusAnggota.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusAnggota.setText("HAPUS");
        btnHapusAnggota.setBorder(null);
        btnHapusAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusAnggotaActionPerformed(evt);
            }
        });

        iKelaminAnggota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        iStatusAnggota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mahasiswa", "Guru", "Pekerja" }));

        jLabel17.setText("ID Anggota");

        jLabel18.setText("Nama Anggota");

        jLabel19.setText("Tempat Lahir");

        jLabel20.setText("Tanggal Lahir");

        jLabel21.setText("Kelamin");

        jLabel22.setText("Status");

        jLabel23.setText("Alamat");

        jLabel24.setText("Nomor Telepon");

        btnClearAnggota.setText("Clear");
        btnClearAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAnggotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AnggotaMasterLayout = new javax.swing.GroupLayout(AnggotaMaster);
        AnggotaMaster.setLayout(AnggotaMasterLayout);
        AnggotaMasterLayout.setHorizontalGroup(
            AnggotaMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnggotaMasterLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(AnggotaMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AnggotaMasterLayout.createSequentialGroup()
                        .addComponent(btnHapusAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AnggotaMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(iNomorTeleponAnggota)
                        .addComponent(jLabel24)
                        .addComponent(jLabel23)
                        .addComponent(jLabel22)
                        .addComponent(iStatusAnggota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iAlamatAnggota)
                        .addComponent(iKelaminAnggota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addComponent(jLabel20)
                        .addComponent(jLabel19)
                        .addComponent(iTempatLahirAnggota)
                        .addGroup(AnggotaMasterLayout.createSequentialGroup()
                            .addGroup(AnggotaMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(iIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(AnggotaMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(iNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(AnggotaMasterLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClearAnggota))
                        .addComponent(iTanggalLahirAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 102, Short.MAX_VALUE))
        );
        AnggotaMasterLayout.setVerticalGroup(
            AnggotaMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnggotaMasterLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(AnggotaMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnClearAnggota))
                .addGap(19, 19, 19)
                .addGroup(AnggotaMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AnggotaMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(8, 8, 8)
                .addComponent(iTempatLahirAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iTanggalLahirAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iKelaminAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iStatusAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iAlamatAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iNomorTeleponAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(AnggotaMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("TRANSAKSI");

        iIdAnggotaTransaksi.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iIdAnggotaTransaksi.setForeground(new java.awt.Color(204, 204, 204));
        iIdAnggotaTransaksi.setToolTipText("");
        iIdAnggotaTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iIdAnggotaTransaksiActionPerformed(evt);
            }
        });

        iEditTransaksi.setBackground(new java.awt.Color(0, 51, 255));
        iEditTransaksi.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        iEditTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        iEditTransaksi.setText("EDIT");
        iEditTransaksi.setBorder(null);
        iEditTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iEditTransaksiActionPerformed(evt);
            }
        });

        btnTambahTransaksi.setBackground(new java.awt.Color(0, 153, 51));
        btnTambahTransaksi.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnTambahTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahTransaksi.setText("TAMBAH");
        btnTambahTransaksi.setBorder(null);
        btnTambahTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahTransaksiActionPerformed(evt);
            }
        });

        iHapusTransaksi.setBackground(new java.awt.Color(255, 0, 0));
        iHapusTransaksi.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        iHapusTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        iHapusTransaksi.setText("HAPUS");
        iHapusTransaksi.setBorder(null);

        iIdPinjamTransaksi.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iIdPinjamTransaksi.setForeground(new java.awt.Color(204, 204, 204));
        iIdPinjamTransaksi.setToolTipText("");
        iIdPinjamTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iIdPinjamTransaksiActionPerformed(evt);
            }
        });

        btnCariTunggakan.setBackground(new java.awt.Color(153, 153, 0));
        btnCariTunggakan.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnCariTunggakan.setForeground(new java.awt.Color(255, 255, 255));
        btnCariTunggakan.setText("CARI TUNGGAKAN");
        btnCariTunggakan.setBorder(null);

        jLabel6.setText("ID Pinjam");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setText("Film");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pinjam", "Kembali", "Perpanjang" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pinjam", "Kembali", "Perpanjang" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("Keterangan");

        btnLogin10.setBackground(new java.awt.Color(0, 51, 255));
        btnLogin10.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnLogin10.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin10.setText("EDIT");
        btnLogin10.setBorder(null);
        btnLogin10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin10ActionPerformed(evt);
            }
        });

        jLabel9.setText("Film");

        jLabel10.setText("Keterangan");

        iKeteranganTransaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pinjam", "Kembali", "Perpanjang" }));

        jLabel25.setText("Tanggal Pinjam");

        jLabel26.setText("Tanggal Kembali");

        jLabel27.setText("Anggota");

        jLabel28.setText("ID Anggota");

        iIdFilmTransaksi.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        iIdFilmTransaksi.setForeground(new java.awt.Color(204, 204, 204));
        iIdFilmTransaksi.setToolTipText("");
        iIdFilmTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iIdFilmTransaksiActionPerformed(evt);
            }
        });

        jLabel29.setText("ID Film");

        jLabel30.setText("Denda");

        lIdDetailTransaksi.setText("ID Detail");

        clearInputTransaksi.setText("Clear");

        javax.swing.GroupLayout TransaksiMasterLayout = new javax.swing.GroupLayout(TransaksiMaster);
        TransaksiMaster.setLayout(TransaksiMasterLayout);
        TransaksiMasterLayout.setHorizontalGroup(
            TransaksiMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransaksiMasterLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(TransaksiMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TransaksiMasterLayout.createSequentialGroup()
                        .addComponent(iHapusTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iEditTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TransaksiMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel30)
                        .addComponent(jLabel27)
                        .addComponent(jLabel28)
                        .addComponent(jLabel26)
                        .addComponent(jLabel25)
                        .addGroup(TransaksiMasterLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lIdDetailTransaksi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                            .addComponent(clearInputTransaksi))
                        .addComponent(iKeteranganTransaksi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(iTanggalPinjamTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iTanggalKembaliTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iNamaAnggotaTransaksi)
                        .addComponent(iJudulFilmTransaksi)
                        .addGroup(TransaksiMasterLayout.createSequentialGroup()
                            .addGroup(TransaksiMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(iIdPinjamTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(iIdAnggotaTransaksi))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(TransaksiMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCariTunggakan, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(TransaksiMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(iIdFilmTransaksi))))
                        .addComponent(iDendaTransaksi)))
                .addGap(0, 102, Short.MAX_VALUE))
        );
        TransaksiMasterLayout.setVerticalGroup(
            TransaksiMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransaksiMasterLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(TransaksiMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lIdDetailTransaksi)
                    .addComponent(clearInputTransaksi))
                .addGap(9, 9, 9)
                .addGroup(TransaksiMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransaksiMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iIdPinjamTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iIdFilmTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransaksiMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iIdAnggotaTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnCariTunggakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iNamaAnggotaTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iJudulFilmTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addComponent(iKeteranganTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iTanggalPinjamTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iTanggalKembaliTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iDendaTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(TransaksiMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iEditTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iHapusTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AnggotaMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TransaksiMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(FilmMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(FilmMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnggotaMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TransaksiMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Form.setViewportView(Container);

        tableDisplay1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDisplay1);

        javax.swing.GroupLayout container2Layout = new javax.swing.GroupLayout(container2);
        container2.setLayout(container2Layout);
        container2Layout.setHorizontalGroup(
            container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, container2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        container2Layout.setVerticalGroup(
            container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, container2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(container2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(Form, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Form, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1320, 830));

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));

        btnFilmPage.setText("FILM");
        btnFilmPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmPageActionPerformed(evt);
            }
        });

        btnAnggotaPage.setText("ANGGOTA");
        btnAnggotaPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnggotaPageActionPerformed(evt);
            }
        });

        btnTransaksiPage.setText("TRANSAKSI");
        btnTransaksiPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiPageActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("MASTER");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("REPORT");

        jButton4.setText("FILM");

        jButton5.setText("ANGGOTA");

        jButton6.setText("TRANSAKSI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(btnFilmPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnggotaPage, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnTransaksiPage, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnFilmPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnggotaPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransaksiPage)
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iKodeFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iKodeFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iKodeFilmActionPerformed

    private void iJudulFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iJudulFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iJudulFilmActionPerformed

    private void iGenreFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iGenreFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iGenreFilmActionPerformed

    private void iTahunFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iTahunFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iTahunFilmActionPerformed

    private void iAsalFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAsalFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iAsalFilmActionPerformed

    private void iStokFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iStokFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iStokFilmActionPerformed

    private void btnEditFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFilmActionPerformed
        film.ubahDataFilm();
    }//GEN-LAST:event_btnEditFilmActionPerformed

    private void btnAnggotaPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnggotaPageActionPerformed
        page = 2;
        choosePage(page);
    }//GEN-LAST:event_btnAnggotaPageActionPerformed

    private void btnTransaksiPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiPageActionPerformed
        page = 3;
        choosePage(page);
    }//GEN-LAST:event_btnTransaksiPageActionPerformed

    private void iIdAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iIdAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iIdAnggotaActionPerformed

    private void iNamaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iNamaAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iNamaAnggotaActionPerformed

    private void iTempatLahirAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iTempatLahirAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iTempatLahirAnggotaActionPerformed

    private void iAlamatAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAlamatAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iAlamatAnggotaActionPerformed

    private void iNomorTeleponAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iNomorTeleponAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iNomorTeleponAnggotaActionPerformed

    private void btnEditAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAnggotaActionPerformed
        anggota.ubahDataAnggota();
    }//GEN-LAST:event_btnEditAnggotaActionPerformed

    private void iIdAnggotaTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iIdAnggotaTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iIdAnggotaTransaksiActionPerformed

    private void iEditTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iEditTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iEditTransaksiActionPerformed

    private void iIdPinjamTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iIdPinjamTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iIdPinjamTransaksiActionPerformed

    private void btnLogin10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin10ActionPerformed

    private void btnSimpanFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanFilmActionPerformed
        film.simpanDataFilm();
    }//GEN-LAST:event_btnSimpanFilmActionPerformed

    private void btnClearInputFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearInputFilmActionPerformed
        film.clearInputFilm();
    }//GEN-LAST:event_btnClearInputFilmActionPerformed

    private void btnHapusFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusFilmActionPerformed
        film.hapusDataFilm();
    }//GEN-LAST:event_btnHapusFilmActionPerformed

    private void btnFilmPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmPageActionPerformed
        page = 1;
        choosePage(page);
    }//GEN-LAST:event_btnFilmPageActionPerformed

    private void tableDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDisplayMouseClicked
        try {
            int baris = tableDisplay.getSelectedRow();
            if (page == 1) {            
                film.mouseClickFilm(baris);
            } else if (page == 2) {
                anggota.mouseClickAnggota(baris);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Maaf terjadi kesalahan pada bagian : \n [" + e.toString() + "]");
        }
    }//GEN-LAST:event_tableDisplayMouseClicked

    private void iSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iSearchKeyPressed
        if (page == 1) {            
            film.cariFilm();
        } else if (page == 2) {
            anggota.cariAnggota();
        }
    }//GEN-LAST:event_iSearchKeyPressed

    private void btnClearAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAnggotaActionPerformed
        anggota.clearInputAnggota();
    }//GEN-LAST:event_btnClearAnggotaActionPerformed

    private void btnTambahAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahAnggotaActionPerformed
        anggota.simpanDataAnggota();
    }//GEN-LAST:event_btnTambahAnggotaActionPerformed

    private void btnHapusAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusAnggotaActionPerformed
        anggota.hapusDataAnggota();
    }//GEN-LAST:event_btnHapusAnggotaActionPerformed

    private void iSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iSearchActionPerformed

    private void iIdFilmTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iIdFilmTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iIdFilmTransaksiActionPerformed

    private void btnTambahTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnggotaMaster;
    private javax.swing.JPanel Container;
    private javax.swing.JPanel FilmMaster;
    private javax.swing.JScrollPane Form;
    private javax.swing.JPanel TransaksiMaster;
    private javax.swing.JButton btnAnggotaPage;
    private javax.swing.JButton btnCariTunggakan;
    private javax.swing.JButton btnClearAnggota;
    private javax.swing.JButton btnClearInputFilm;
    private javax.swing.JButton btnEditAnggota;
    private javax.swing.JButton btnEditFilm;
    private javax.swing.JButton btnFilmPage;
    private javax.swing.JButton btnHapusAnggota;
    private javax.swing.JButton btnHapusFilm;
    private javax.swing.JButton btnLogin10;
    private javax.swing.JButton btnSimpanFilm;
    private javax.swing.JButton btnTambahAnggota;
    private javax.swing.JButton btnTambahTransaksi;
    private javax.swing.JButton btnTransaksiPage;
    private javax.swing.JButton clearInputTransaksi;
    private javax.swing.JPanel container2;
    private javax.swing.JTextField iAlamatAnggota;
    private javax.swing.JTextField iAsalFilm;
    private javax.swing.JTextField iDendaTransaksi;
    private javax.swing.JButton iEditTransaksi;
    private javax.swing.JTextField iGenreFilm;
    private javax.swing.JButton iHapusTransaksi;
    private javax.swing.JTextField iIdAnggota;
    private javax.swing.JTextField iIdAnggotaTransaksi;
    private javax.swing.JTextField iIdFilmTransaksi;
    private javax.swing.JTextField iIdPinjamTransaksi;
    private javax.swing.JTextField iJudulFilm;
    private javax.swing.JTextField iJudulFilmTransaksi;
    private javax.swing.JComboBox<String> iKelaminAnggota;
    private javax.swing.JComboBox<String> iKeteranganTransaksi;
    private javax.swing.JTextField iKodeFilm;
    private javax.swing.JTextField iNamaAnggota;
    private javax.swing.JTextField iNamaAnggotaTransaksi;
    private javax.swing.JTextField iNomorTeleponAnggota;
    private javax.swing.JTextField iSearch;
    private javax.swing.JComboBox<String> iStatusAnggota;
    private javax.swing.JTextField iStokFilm;
    private javax.swing.JTextField iTahunFilm;
    private com.toedter.calendar.JDateChooser iTanggalKembaliTransaksi;
    private com.toedter.calendar.JDateChooser iTanggalLahirAnggota;
    private com.toedter.calendar.JDateChooser iTanggalPinjamTransaksi;
    private javax.swing.JTextField iTempatLahirAnggota;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lIdDetailTransaksi;
    private javax.swing.JTable tableDisplay;
    private javax.swing.JTable tableDisplay1;
    // End of variables declaration//GEN-END:variables
}
